import { DateTime } from 'luxon';
import type { Logger } from '../utils/logger.js';
import type { Task } from '../tasks/types.js';
import type { CalendarEvent, StudyBlockRequest, StudyBlockWriter } from './types.js';
import { computeFreeWindows } from './freeWindows.js';
import { windowMinutes, type TimeWindow } from '../utils/time.js';

export interface StudyBlockPlanOptions {
  zone: string;
  now: DateTime;
  /** How far ahead to place blocks. */
  horizonDays: number;
  maxSessionMinutes: number;
  /** Gap left before and after each block so the day is not wall-to-wall. */
  bufferMinutes: number;
  dayStart: string;
  dayEnd: string;
  /** Ceiling on scheduled study minutes per day; prevents overfilling. */
  maxMinutesPerDay: number;
}

export interface PlannedStudyBlock extends StudyBlockRequest {
  taskId: string;
  sessionIndex: number;
  sessionCount: number;
}

/**
 * Splits a task into sessions and places them in real free time before the
 * deadline.
 *
 * Rules that come straight from the product spec:
 *  - never schedule after the due date
 *  - never exceed `maxSessionMinutes` in one sitting
 *  - leave buffers, and never consume every free minute of a day
 *  - large assignments become several sessions across several days
 */
export function planStudyBlocks(
  tasks: Task[],
  events: CalendarEvent[],
  options: StudyBlockPlanOptions,
): PlannedStudyBlock[] {
  const horizonEnd = options.now.plus({ days: options.horizonDays }).endOf('day');

  // Free time is computed once, then consumed as blocks are placed, so two
  // tasks can never be scheduled on top of each other.
  const remaining: TimeWindow[] = [];
  for (let dayOffset = 0; dayOffset <= options.horizonDays; dayOffset += 1) {
    const day = options.now.plus({ days: dayOffset });
    const from = dayOffset === 0 ? options.now : day.startOf('day');
    remaining.push(
      ...computeFreeWindows(events, options.zone, {
        from,
        to: day.endOf('day'),
        dayStart: options.dayStart,
        dayEnd: options.dayEnd,
        minimumMinutes: 15,
      }),
    );
  }

  const scheduledPerDay = new Map<string, number>();
  const planned: PlannedStudyBlock[] = [];

  // Earliest deadline first: the most constrained work gets the best slots.
  const candidates = tasks
    .filter((task) => task.dueAt !== null)
    .filter((task) => task.status === 'ready' || task.status === 'active')
    .sort((a, b) => (a.dueAt ?? '').localeCompare(b.dueAt ?? ''));

  for (const task of candidates) {
    const due = DateTime.fromISO(task.dueAt as string, { zone: options.zone });
    if (!due.isValid || due <= options.now || due > horizonEnd) continue;

    const sessionCount = Math.max(1, Math.ceil(task.estimatedMinutes / options.maxSessionMinutes));
    const sessionMinutes = Math.min(
      options.maxSessionMinutes,
      Math.ceil(task.estimatedMinutes / sessionCount),
    );

    let placed = 0;
    for (let index = 0; index < remaining.length && placed < sessionCount; index += 1) {
      const window = remaining[index];
      if (!window) continue;

      // Hard rule: study time must land before the deadline.
      if (window.start >= due) continue;

      const usableEnd = window.end < due ? window.end : due;
      const available = windowMinutes({ start: window.start, end: usableEnd });
      const needed = sessionMinutes + options.bufferMinutes;
      if (available < needed) continue;

      const dayKeyValue = window.start.toFormat('yyyy-LL-dd');
      const already = scheduledPerDay.get(dayKeyValue) ?? 0;
      if (already + sessionMinutes > options.maxMinutesPerDay) continue;

      const start = window.start.plus({ minutes: options.bufferMinutes });
      const end = start.plus({ minutes: sessionMinutes });

      planned.push({
        taskId: task.id,
        sessionIndex: placed + 1,
        sessionCount,
        title: `${task.course ?? task.category.toUpperCase()} — ${task.title}`,
        start,
        end,
        description: [
          task.nextAction ? `Start: ${task.nextAction}` : null,
          `Session ${placed + 1} of ${sessionCount}`,
          'Generated by execution-agent',
        ]
          .filter(Boolean)
          .join('\n'),
      });

      scheduledPerDay.set(dayKeyValue, already + sessionMinutes);
      // Consume the used part of the window so later tasks see what is left.
      remaining[index] = { start: end, end: window.end };
      placed += 1;
    }
  }

  return planned;
}

export interface SyncStudyBlocksOptions {
  writer: StudyBlockWriter;
  calendarName: string;
  from: Date;
  to: Date;
  logger: Logger;
}

/**
 * Writes planned blocks into the agent's dedicated calendar, replacing the
 * agent's own previous blocks in that window. It never touches events it did
 * not create — the writer implementations refuse foreign calendars.
 */
export async function syncStudyBlocks(
  planned: PlannedStudyBlock[],
  options: SyncStudyBlocksOptions,
): Promise<{ created: number; removed: number }> {
  const { writer, calendarName, logger } = options;
  await writer.ensureCalendar(calendarName);

  const existing = await writer.listAgentBlocks(calendarName, options.from, options.to);
  const wanted = new Set(
    planned.map((block) => `${block.title}|${block.start.toISO()}|${block.end.toISO()}`),
  );

  let removed = 0;
  for (const event of existing) {
    const key = `${event.title}|${event.start.toISOString()}|${event.end.toISOString()}`;
    if (!wanted.has(key)) {
      if (await writer.deleteBlock(calendarName, event.id)) removed += 1;
    }
  }

  const existingKeys = new Set(
    existing.map((event) => `${event.title}|${event.start.toISOString()}|${event.end.toISOString()}`),
  );

  let created = 0;
  for (const block of planned) {
    const key = `${block.title}|${block.start.toISO()}|${block.end.toISO()}`;
    if (existingKeys.has(key)) continue;
    const id = await writer.createBlock(calendarName, block);
    if (id) created += 1;
  }

  logger.info({ created, removed, calendarName }, 'synced study blocks');
  return { created, removed };
}
